[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = "true"

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.test]
command = "cargo"
args = ["test"]

[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.clippy]
install_crate = "clippy"
command = "cargo"
args = ["clippy", "--all-targets", "--all-features"]

[tasks.ci-build]
command = "cargo"
args = ["build", "-v", "--all-features"]
dependencies = ["clean"]

[tasks.ci-test]
command = "cargo"
args = ["test", "-v", "--all-features"]
dependencies = ["ci-build"]

[tasks.pre-commit]
dependencies = ["format", "clippy"]

[tasks.pre-push]
dependencies = ["test"]
